### ISSUE TITLE
Move all bindings related projects to a dedicated github organization

### ISSUE THREAD

**Issue by Ingvord** [tango-controls-migration-tests/TangoTickets#11]
Similar to #5 we can create __tango-controls-bindings__ org and move all bindings related projects there.

Should we do it? 

@nleclercq this will mostly affect your projects. What are your thoughts on this?

**Comment by nleclercq** [comment]
@Ingvord no objection. 
If you guys think that it's better for the projects management then let's go for a dedicated repo for the bindings.
