### ISSUE TITLE
ATKPAnel :  boolean attribute are check unexpectedly 

### ISSUE THREAD

**Issue by alainbuteau** [tango-controls-migration-tests/TangoTickets#16]
I already posted such an issue in the past on SoruceForge  but despite using now the latest versions of ATK (9.2.24) the issue is still there

I copy/paste here the content of the SF tickets https://sourceforge.net/p/tango-cs/bugs/715/ and https://sourceforge.net/p/tango-cs/bugs/153/

Any ideas in ATK Team on this issue that can be very blocking seen from the control systems points of view (let's imagine if the meaning of the boolean is "Stop motor" )? 

**Scenario :**
- ATPanel is started on a device which has 1 boolean attribut READ/WRITE.
- Without direct user interaction on the ATKPanel, we observed sometimes that the boolean if written.

This looks a little bit like an old issue https://sourceforge.net/p/tango-cs/bugs/153/ but up to now we do not have a clear scenario to reproduce

Nevertheless we are sure the boolean is written through ATKPanel thanks to the blackbox of the device who proved that the client application which wrote the boolean attribute was ATKPanel

So without such scenario , could you check in the ATKPanel code which user interaction could explain such an unexpected behaviour ?

Thanks

**Comment by alainbuteau** [comment]
Jean Luc 
I cannot assign the ticket to Faranguiss 
Could you please tell her with still have the issue open and disturbing for our users

**Comment by faranguiss-poncet** [comment]
In AtkPanel you can set a read/write boolean attribute in two manners : 
- By selecting the True or False in the combo box
- or by clicking inside the checkbox
The boolean scalar attributes can be modified either by their viewer (checkbox) or by their setter (combobox).
Have you checked which AtkPanel (process id) from which host has modified the boolean attribute. Then ask the user if (s)he has clicked on the checkbox??

The atkpanel and / or ATK does not a setAttribute spontaneously. It is always in response to a user action.

Need more precisions.
Faranguiss

**Comment by alainbuteau** [comment]
Sorry Faranguiss to have difficulties to help you to reproduce the problem.
- But we have many testimonies here that tell this "behaviour" exists in the real world and therefore this is a real bug 
-  I suspect that in fact there is a user action (the user clicked somewhere in the screen but not on the combobox itself) and that for some reason ATKPanel is notified that a user input is received on this combox 
- I 'll ask our users to give more details (do they have multiple ATKPanel opens on the same device ? , on many different devices?  , these ATKPanel are runned from the same jive , ..? ) 
- on your side , could have a discussion with Jean Luc for instance to see if they can be subtile interaction on input focus management between jive and ATKPanl because for sure , in our case ATKPanel is launched from jive in all cases
