### ISSUE TITLE
ATKPanel and test Device show different values for some  DEV_LONG64 attributes

### ISSUE THREAD

**Issue by alainbuteau** [tango-controls-migration-tests/TangoTickets#17]
* Test Device : 
_Attribute: PLCSERVERV3/CPU315/PLCDV.1/Type_LINT
Duration: 1 msec
measure date: 26/02/2018 10:16:06 + 159ms
quality: VALID
Read:	-994074541749903631_

* ATKPAnel value : is slightly different  **-994074541749903616 instead of -994074541749903631** which is expected and displayed in Test Device

**Comment by faranguiss-poncet** [comment]
Hello,
All numeric values are converted into double values inside ATK. Consequently we don't have enough space in a double mantissa to encode 64 bits integer values.

This issue cannot be fixed without a huge work in many classes of ATK library.

I close this issue without fixing.
