### ISSUE TITLE
Java Device Servers : add the possibility to set the setpoint of a static (non dynamic) attribute

### ISSUE THREAD

**Issue by faranguiss-poncet** [tango-controls-migration-tests/TangoTickets#18]
We sometimes need to update the write part of an attribute when the attribute getter method is called.
This is particularly useful when the Java Device Server wraps another device attribute and needs to update the read part and also the write part of the attribute according to the underlying attribute.

Today inside the getter method of the attribute we can eventually call the methods like setQuality or setTime (org.tango.server.attribute.AttributeValue) of the attributeValue. But no method is provided to set (update) the write part of the attribute.

A solution is proposed today but unfortunately it applies ONLY to the dynamic attributes.
Could you please add this feature in JTango?
Thank you in advance.
Faranguiss

**Comment by andygotz** [comment]
Progress on this issue will be tracked in issue https://github.com/tango-controls/JTango/issues/55
