### ISSUE TITLE
is 9.3.0 cppTango ready?

### ISSUE THREAD

**Issue by cmft** [tango-controls-migration-tests/TangoTickets#26]
Dear Tangoers,
Is the cpp 9.3.0 version ready? If yes,  is the `TangoSourceDistribution` adapted? 

There is a new release of PyTango based on that: https://github.com/tango-controls/pytango/releases/tag/v9.3.0 and we would like to test it af ALBA. But we would like to know the status of the projects.

@tiagocoutinho  which version of cpp did you use?

Best,
Carlos

**Comment by bourtemb** [comment]
Hi Carlos,

cppTango 9.3.3 will hopefully be ready on Thursday or Friday this week.
You can follow the status on this ticket: https://github.com/tango-controls/cppTango/issues/543

The TangoSourceDistribution will be using 9.3.3 as soon as the tag will have been created.

**Comment by cmft** [comment]
Many thanks @bourtemb

**Comment by tiagocoutinho** [comment]
@cmft, for PyTango 9.3.0 I used [9.3.2-alpha.1](https://github.com/tango-controls/TangoSourceDistribution/releases/tag/9.3.2-alpha.1) tango package which contains cppTango lib 9.3.2.

I announced it on the tango mailing list but there is a problem with my account. I am trying to fix it now.
