### ISSUE TITLE
subscribe_event fails between Tango mixing

### ISSUE THREAD

**Issue by cmft** [tango-controls-migration-tests/TangoTickets#3]
Hi,
I saw a strange behaviour between Tango9 (client) and Tango7 (server). If I subscribed (change event) to a TangoTest short attribute, that is running with Tango7 (7.2.6 + patches),  using a Tango9 client  (9.2.5a). I got events with UNKNOWN data format and without values.

In our test we only detect problems with short_scalar attribute the others seem right. 

I attached my client.
[eventclient.zip](https://github.com/tango-controls/TangoTickets/files/810013/eventclient.zip)

```
I have received an event for attribute tango://controls01.cells.es:10000/sys/tg_test/1/short_scalar
Wed Mar  1 08:47:30 2017 (1488354450,932103 sec) : short_scalar (dim_x = 1, dim_y = 0, w_dim_x = 1, w_dim_y = 0, Data quality factor = VALID, Data format = SCALAR, Data type = DevShort)
Element number [0] = 5
Element number [1] = 10
ev_id1 = 1
I have received an event for attribute tango://controls01.cells.es:10000/sys/tg_test/1/short_scalar
Wed Mar  1 08:47:33 2017 (1488354453,932359 sec) : short_scalar (dim_x = 1, dim_y = 0, w_dim_x = 1, w_dim_y = 0, Data quality factor = VALID, Data format = UNKNOWN, Element number [0] = 1
Element number [1] = 10
```

**Comment by bourtemb** [comment]
Hi Carlos,
Thanks for the bug report.
Your bug report is very similar to the following bug which was fixed for Tango9 Client subscribing to Tango 8 server:
https://github.com/tango-controls/cppTango/issues/248
I think I fixed your problem in the following Pull Request I just created:
https://github.com/tango-controls/cppTango/pull/354
Kind regards
Reynald

**Comment by Ingvord** [comment]
Fix is merged into [Tango 9 LTS](https://github.com/tango-controls/cppTango/tree/tango-9-lts)

I would provide a test case for this to close the issue.
