### ISSUE TITLE
Tango Logging: unable to set a path with capital letters (from Jive)

### ISSUE THREAD

**Issue by flanglois** [tango-controls-migration-tests/TangoTickets#36]
It happens if the device runs on Linux and not on Windows
it seems that something minimize the path, which become a problem on Linux but not on Windows, which is case insensitive regarding the paths and files.

here on a Windows host:
![image](https://user-images.githubusercontent.com/2440081/83269996-2a187b00-a1c8-11ea-88cd-cfc48b434201.png)

**Comment by bourtemb** [comment]
@JeanLucPons , do you know whether this behaviour is coming from jive or from somewhere else?
