### ISSUE TITLE
Device export / DeviceProxy connection problem in Kubernetes pod

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls-migration-tests/TangoTickets#38]
For the SKA project we are running our Tango device servers in docker containers launched via Kubernetes (k8s).  Sometimes we notice that `DeviceProxy` instances do not connect to the intended device.  The variability is possibly related to the startup order of the containers.

Example setup:
- pod A
  - container 1:
    - device server 1
      - device: class `Master`, name `my/master/1`
  - container 2:
    - device server 2
      - device:  class `WorkerA`, name `my/worker/2a`
      - device:  class `WorkerB`, name `my/worker/2b`
  - container 3:
    - device server 3
      - device:  class `WorkerA`, name `my/worker/3a`
      - device:  class `WorkerB`, name `my/worker/3b`
- pod B
  - container 1:
     - DatabaseDS

I haven't confirmed, but this issue was probably using cppTango 9.3.4-rc2, and PyTango 9.3.1.

The problem doesn't appear to occur every time we start up all the pods.  When the problem is present, creating `DeviceProxy` instances using the same device name gives different results, depending on which container we use for the connection:

#### Container 1 - gets right device (the master):
```
>>> dp = tango.DeviceProxy("my/master/1")
>>> dp
Master(my/master/1)
```

#### Container 2 - gets wrong device (a worker):
```
>>> dp = tango.DeviceProxy("my/master/1")
>>> dp
WorkerA(my/master/1)
```

#### Container 3 - gets right device (the master):
```
>>> dp = tango.DeviceProxy("my/master/1")
>>> dp
Master(my/master/1)
```

From our initial debugging, the issue is that containers running in the same pod get the same hostname.  Thus the connection details exported to the database are no longer unique.  There could be multiple device servers with the same hostname and port.  Does that sound like it would create the problem we are seeing above? 

One option would be to manually specify port number for each device server using `-ORBendPoint giop:tcp:<hostname>:<port>`.  However, it was pointed out in a Tango kernel developers meeting that the ZeroMQ port numbers for events could still cause problems - it is not possible set them statically via the command line.

Our plan to work around this is to change our deployment strategy.  We still want to run each device server in its own container.  However, we will restrict each pod to a single device server.  To logically group device servers that go together we are using StatefulSets instead of pods.   The  changes can be seen [here](https://gitlab.com/ska-telescope/skampi/-/merge_requests/85/), for those that are interested.

I'm not sure if anything could be or should be changed in Tango to support our original deployment strategy.  Probably not.

**Comment by mliszcz** [comment]
Hi @ajoubertza 

Do you have or can provide a database dump (at least device and server tables) and list of TCP ports opened by your device servers? It should ease the debugging.

By default, omniORB listens on ephemeral ports, which are allocated by the kernel, so there should be no difference compared to running all device servers on 'bare metal' (no k8s) on the same machine. Maybe some namespaces come into play when containers are involved, but per my understanding there is no network isolation between containers within the same pod.

**Comment by ajoubertza** [comment]
Hi @mliszcz.

No, I don't have that info (the failure wasn't on my system).  Maybe @Matteo04052017 can provide such info - he did look at the database tables, and has tried to reproduce the problem.

@andrew-bolin has also reported a similar issue when using Docker compose in host network mode. However, with host network mode, a listening port in one container is marked as used in other containers and the host itself, so we should not get port duplication.  The containers would be running in privileged mode, so sharing namespaces.

Yes, we are thinking Linux kernel namespaces has something to do with this.   It seems there are some options to tweak the namespace behaviour in k8s.

**Comment by mliszcz** [comment]
Have you tried changing the port ranges to non-overlapping values before starting the device servers? You can use something like: `sysctl -w net.ipv4.ip_local_port_range="51001 52000"` . I do not know what container runtime you are using but in docker this requires `--privileged`. Setting this option in one container does not impact host or other containers (at least in bridged network setup).

**Comment by ajoubertza** [comment]
Thanks for the suggestion @mliszcz - that's a good idea to try.  However, we won't be trying it since we've decided to follow the StatefulSets approach instead of Pods ([PR here](https://gitlab.com/ska-telescope/skampi/-/merge_requests/85/)).  That way we avoid the problem.
