### ISSUE TITLE
DataBaseds: Does not listen on ipv4 port 10000

### ISSUE THREAD

**Issue by t-b** [tango-controls-migration-tests/TangoTickets#40]
Using debian unstable/tango-9.4-rc6 packages.

- Install: `apt install -t experimental tango-db tango-starter tango-test`
- Use default options when asked
- start database just to be sure `systemctl start tango-db`

Looking who is listening

```
root@debian:/home/thomas/devel/tango-9.3.4-rc6/cppserver/database# netstat -ltnp | grep DataBaseds
tcp        0      0 0.0.0.0:37329           0.0.0.0:*               LISTEN      6840/DataBaseds     
tcp6       0      0 :::10000                :::*                    LISTEN      6840/DataBaseds     
```

reveals that we only listen on port 10000 for ipv6 and on some random port for ipv4.

**Comment by mliszcz** [comment]
Hi @t-b,
Can you actually reach DataBaseds over IPv4? If it works it means that it may be using 'IPv4-mapped IPv6' address. In such case you will get just one entry in netstat output. I've seen some applications doing this but I don't recall now if it was DataBaseds or something else.

See:
https://serverfault.com/questions/755765/httpd-listening-in-ipv6-according-netstat-but-reacheable-in-ipv4
https://unix.stackexchange.com/questions/152612/netstat-why-are-ipv4-daemons-listening-to-ports-listed-only-in-a-inet6

**Comment by mliszcz** [comment]
The random IPv4 port is most likely ephemeral port assigned to zmq event channel.

**Comment by t-b** [comment]
@mliszcz Thanks, this does explain it. I've retried with

```
thomas@debian:~$ TANGO_HOST=127.0.0.1:10000 /usr/lib/tango/TangoTest test
Ready to accept request
```

and indeed netstat's reporting got me fooled.
