### ISSUE TITLE
An attribute description with non latin letters causes errors.

### ISSUE THREAD

**Issue by GrigoryPrutskov** [tango-controls-migration-tests/TangoTickets#43]
Hi folks

I am facing the following problem:

If I create a tango device server with JTango which contains an attribute with description with cyrillic letters, then an access to the attribute from PyTango will cause errors.

A little example to reproduce this issue:
Java classes:

```
package test;
import org.tango.server.annotation.Attribute;
import org.tango.server.annotation.AttributeProperties;
import org.tango.server.annotation.Device;
@Device
public class TestDevice {
    @Attribute(name = "attribute")
    @AttributeProperties(description = "Какая-то кириллица")
    public double getAttribute() {
        return 123;
    }
}
```

```
package test;
import org.tango.server.ServerManager;
public class TestServer {
    public static void main(final String[] args) {
        ServerManager.getInstance().addClass(test.TestDevice.class.getSimpleName(), test.TestDevice.class);
        ServerManager.getInstance().start(args, TestServer.class);
    }
}
```
The next step is a creation of a test device server in a tango db. For example, it will be "TestServer/TestServer0" instance with "Test/TestDevices/0" device. 

Compile test.jar and export server by following command:
`java -cp test.jar test.TestServer TestServer0`

After exporting trying to access this attribute from pytango  causes following errors:

```
Python 3.6.8 (default, Apr 16 2020, 01:36:27) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tango import DeviceProxy
>>> proxy = DeviceProxy("Test/TestDevices/0")
>>> proxy.get_attribute_config("attribute")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pytango-9.3.3.dev0-py3.6-linux-x86_64.egg/tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/pytango-9.3.3.dev0-py3.6-linux-x86_64.egg/tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/pytango-9.3.3.dev0-py3.6-linux-x86_64.egg/tango/device_proxy.py", line 825, in __DeviceProxy__get_attribute_config
    return self._get_attribute_config(value)
PyTango.CommunicationFailed: DevFailed[
DevError[
    desc = CORBA unknown system exception !!!!!!!!
  origin = DeviceProxy::get_attribute_config()
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Failed to execute get_attribute_config on device test/testdevices/0
  origin = DeviceProxy::get_attribute_config()
  reason = API_CommunicationFailed
severity = ERR]
]
```
At the same time access to this attribute works fine from JTango (For example, ATKPanel allows to manage it)
But the weirdest part is recompiling java classes with non-cyrillic strings and reexport a server doesn't work, it's needed to delete server from db and create a new one.

System:
Centos 8 x86_64
python 3.6
Tango 9.3.4
pytango 9.3.3
java 1.8.0 openjdk

PS: may be this bug is well known, but I cannot find anything about them :)

**Comment by ajoubertza** [comment]
Hi @GrigoryPrutskov 

I also don't know if there is a well known bug like that!

I tried using PyTango device server (Python 3.8.5, cppTango 9.3.4, Conda environment).  It works fine with a device proxy created using PyTango.

I just modified the [Clock](https://github.com/tango-controls/pytango/blob/develop/examples/Clock/ClockDS.py) example.
```python
class ClockCyrillic(Device):

    display_type = DisplayType(0)

    @attribute(dtype=float, description="Какая-то кириллица")
    def time(self):
        return time.time()

...
```
Register:
```
tango_admin --add-server ClockCyrillic/testCyrillic ClockCyrillic test/clock/cyrillic
```

Run:
```
python ClockDS.py testCyrillic
```


Access via a device proxy, in ipython:
```python
In [1]: import tango

In [2]: dp = tango.DeviceProxy("test/clock/cyrillic")

In [3]: dp.get_attribute_config("time")
Out[3]: AttributeInfoEx(alarms = AttributeAlarmInfo(delta_t = 'Not specified', delta_val = 'Not specified', extensions = [], max_alarm = 'Not specified', max_warning = 'Not specified', min_alarm = 'Not specified', min_warning = 'Not specified'), data_format = tango._tango.AttrDataFormat.SCALAR, data_type = tango._tango.CmdArgType.DevDouble, description = 'Какая-то кириллица', disp_level = tango._tango.DispLevel.OPERATOR, display_unit = 'No display unit', enum_labels = [], events = AttributeEventInfo(arch_event = ArchiveEventInfo(archive_abs_change = 'Not specified', archive_period = 'Not specified', archive_rel_change = 'Not specified', extensions = []), ch_event = ChangeEventInfo(abs_change = 'Not specified', extensions = [], rel_change = 'Not specified'), per_event = PeriodicEventInfo(extensions = [], period = '1000')), extensions = [], format = '%6.2f', label = 'time', max_alarm = 'Not specified', max_dim_x = 1, max_dim_y = 0, max_value = 'Not specified', memorized = tango._tango.AttrMemorizedType.NONE, min_alarm = 'Not specified', min_value = 'Not specified', name = 'time', root_attr_name = 'Not specified', standard_unit = 'No standard unit', sys_extensions = [], unit = '', writable = tango._tango.AttrWriteType.READ, writable_attr_name = 'None')

In [4]: dp.get_attribute_config("time").description
Out[4]: 'Какая-то кириллица'

In [5]: dp.get_attribute_config(["time"])
Out[5]: [AttributeInfo(data_format = tango._tango.AttrDataFormat.SCALAR, data_type = tango._tango.CmdArgType.DevLong64, description = 'Какая-то кириллица', disp_level = tango._tango.DispLevel.OPERATOR, display_unit = 'No display unit', extensions = [], format = '%d', label = 'time', max_alarm = 'Not specified', max_dim_x = 1, max_dim_y = 0, max_value = 'Not specified', min_alarm = 'Not specified', min_value = 'Not specified', name = 'time', standard_unit = 'No standard unit', unit = '', writable = tango._tango.AttrWriteType.READ, writable_attr_name = 'None')]
```

The first `DevError` exception, with `API_CorbaException` is coming from the cppTango layer, as far as I can tell.


The PyTango DeviceProxy `get_attribute_config` method with a single string ends up in cppTango:  
`DeviceProxy::get_attribute_config(const string &attr_string)`, and that calls `DeviceProxy::get_attribute_config_ex(vector<string> &attr_string_list)`.

The PyTango method can also be called with a sequence, which will end up in a different code path in cppTango. `DeviceProxy::get_attribute_config(vector<string> &attr_string_list)`.  Please try it with a list, maybe that will give us another clue:

```python
proxy.get_attribute_config(["attribute"])
```

I don't have JTango to try to reproduce the error that way.
It would be interesting if someone could try with JTango and cppTango `DeviceProxy` directly.

**Comment by GrigoryPrutskov** [comment]
@ajoubertza 
Thanks you for testing
I've checked your example and it works fine on my system. Nevertheless, access to an attribute even as list still gets me same error.

**Comment by ajoubertza** [comment]
@GrigoryPrutskov OK.  Do the server logs show anything interesting?  If I run with `-v5`, I get:

using single string (so cppTango `get_attribute_config_ex`):
```
1607356631 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic In get_monitor() att_config, thread = 6, ctr = 0
1607356631 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Device_5Impl::get_attribute_config_5 arrived
1607356631 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Leaving Device_3Impl::get_attribute_config_5
1607356631 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic In rel_monitor() att_config, ctr = 1, thread = 6
1607356631 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Signalling !
```

And using a list (so cppTango `get_attribute_config`):
```
1607356674 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic In get_monitor() att_config, thread = 6, ctr = 0
1607356674 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Device_2Impl::get_attribute_config_2 arrived
1607356674 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Leaving Device_2Impl::get_attribute_config_2
1607356674 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic In rel_monitor() att_config, ctr = 1, thread = 6
1607356674 [139858858538752] DEBUG dserver/ClockCyrillic/testCyrillic Signalling !
```

Other than that, you'd have to try setting a break point in the cppTango code.

**Comment by bourtemb** [comment]
This might be due to the native code set used by default by omniORB which is different than the default one from JacORB.
If I remember correctly, JacORB uses UTF8 by default whereas omniORB uses ISO 8859-1 (Latin 1) for char and string (http://omniorb.sourceforge.net/omni42/omniORB/omniORB008.html).
I would suggest to try to configure omniORB to use UTF8 as nativeCharCodeSet.

I think you can test that easily by setting ORBnativeCharCodeSet environment variable to "UTF-8".

export ORBnativeCharCodeSet=UTF-8

If you want this permanently, you can also edit a file named /etc/omniORB.cfg with the following content:
```
nativeCharCodeSet=UTF-8
```

Please refer to the following page to know all the different ways to set omniORB parameters:
http://omniorb.sourceforge.net/omni42/omniORB/omniORB004.html

I'm not surprised you needed to erase the server and recreate it in the database because the data with the non latin letters was already stored in the database. And Tango was trying to retrieve this data when you were restarting the device server.

Hoping this helps a bit.
