### ISSUE TITLE
Travis shutdown: Impact and next steps

### ISSUE THREAD

**Issue by t-b** [tango-controls-migration-tests/TangoTickets#44]
[Here](https://github.com/search?l=&p=1&q=org%3Atango-controls+filename%3A.travis.yml&ref=advsearch&type=Code) is the list of `.travis.yml` files in the tango-controls organization. There are at the moment eleven matches.

**Comment by cpascual** [comment]
Some steps towards the migration were done:

- we created the ["gitlab-migration" team](https://github.com/orgs/tango-controls/teams/gitlab-migration). Feel free to request joining
- we created [a kanban board to coordinate migration tasks](https://github.com/tango-controls/TangoTickets/projects/1)
- we created [this repo](https://github.com/tango-controls/gitlab-migration-tools) with tools useful for the migration
- we created the @tango-controls-bot account to be used for the migration (with privileges both in GH and in GL)

**Comment by t-b** [comment]
- https://github.com/tango-controls/TangoSourceDistribution/pull/99
- https://github.com/tango-controls/tango-doc/pull/373
- https://github.com/tango-controls/cppTango/pull/825
- https://github.com/tango-controls/cppTango/pull/820
