### ISSUE TITLE
Cannot connect to the MAX-IV’s repository

### ISSUE THREAD

**Issue by weibu** [tango-controls-migration-tests/TangoTickets#49]
Hi,
I was trying to install Tango on CentOS 7 by following this instruction https://tango-controls.readthedocs.io/en/latest/installation/tango-on-linux.html#centos 
but it seems I could not connect to the MAX-IV’s repository. Here is the error message "http://pubrepo.maxiv.lu.se/rpm/el7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://pubrepo.maxiv.lu.se/rpm/el7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30000 milliseconds')"

**Comment by andygotz** [comment]
@beenje can you help @weibu ?

**Comment by beenje** [comment]
I created an internal ticket. IT will look at it.

**Comment by beenje** [comment]
Issue has been fixed.
@weibu could you please try again and confirm?

**Comment by weibu** [comment]
Yes, the connection has been restored. Thanks.

**Comment by beenje** [comment]
Thanks for the feedback.
