### ISSUE TITLE
Extract hdbpp related repos in a dedicated organization

### ISSUE THREAD

**Issue by Ingvord** [tango-controls-migration-tests/TangoTickets#5]
I would suggest to create a special organization _libhdbpp_ and transfer related repos to it. 

Since libhdbpp counts 10 repos it definitely deserves a dedicated organization. Plus this will make _tango-contorls_ much cleaner.

Overall structure will also benefit, for instance a link to a single organization (_libhdbpp_) from the main site seems much more logical etc

**Comment by bourtemb** [comment]
I agree it would make sense to have a dedicated organization for HDB++ (lib and GUIs).
We just need to agree on the name (libhdbpp does no fit since there will be GUIs involved here too).
- hdbpp
- hdbplusplus
- tango-hdbpp
- tango-controls-hdbpp ?

**Comment by Ingvord** [comment]
I vote for __tango-controls-hdbpp__ alternatively __tango-hdbpp__ (it is shorter, but I think we should always refer to _tango-controls_)

**Comment by Pascal-Verdier** [comment]
I vote for tango-controls-hdbpp too.
It is clearer.

**Comment by lorenzopivetta** [comment]
Havin a separate repo is fine for me. However l'd prefer **hdppp** or **tango-hdbpp**, tango-controls-hdbpp is too long.

**Comment by gscalam** [comment]
I have a question:
are there (or are forseen) other tango-controls related organizations?
In case the answer is yes a common prefix should be found for everyone (tango-controls-*, tango-*, tc-*, ...)
So my preferences are:
1) <tango_common_prefix>-hdbpp
2) hdbpp

**Comment by Ingvord** [comment]
Common prefix makes most sense, and I think _tango-controls_ is the best for this purpose.

**Comment by chedburgh** [comment]
I'd vote for tango-controls-hdbpp also. Same reasons as above, common prefix. Keeping a commom prefix, it would be possible to spin out other components and keep them all looking related in the future.

**Comment by Ingvord** [comment]
A new organization has been created: https://github.com/tango-controls-hdbpp

Should we move repos?

**Comment by bourtemb** [comment]
Thanks Igor, we will do the move when we feel it's more convenient for us.
Could you please give me owner permissions on this new organization so I could invite people working on HDB++ to join and I could administrate this organization?

**Comment by Ingvord** [comment]
@bourtemb Done!

**Comment by Ingvord** [comment]
Looks like it has been done
